# Ce workflow fait la protection du deploy des packages de dépendances. 

name: Snyk Security Gate
on:
  push:
    branches: develop
      #[ feature*/*, dev, pre-prod, prod ] 
  pull_request:
    branches: develop
      #[ feature*/*, dev, pre-prod, prod ]
jobs:
  oss-security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check for high severity oss vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high --fail-on=upgradable
